var SEARCH_DATA = [
  {title:"1.1 AI와 LLM이란?",desc:"AI의 분류, LLM 개념, GPT/Claude/Gemini/LLaMA",url:"index.html#s1-1",kw:"AI LLM GPT Claude Gemini 인공지능"},
  {title:"1.2 생성형 AI의 동작 원리",desc:"토큰화, 추론, 생성 과정",url:"index.html#s1-2",kw:"토큰 추론 생성형 AI 동작원리"},
  {title:"1.3 프롬프트 엔지니어링 기초",desc:"역할 부여, 구체적 지시, 맥락 제공",url:"index.html#s1-3",kw:"프롬프트 엔지니어링 역할 지시"},
  {title:"1.4 주요 AI 도구 소개",desc:"ChatGPT, Claude, Gemini, 국내 AI 도구 비교",url:"index.html#s1-4",kw:"ChatGPT Claude Gemini 뤼튼 클로바노트"},
  {title:"1.5 AI 활용의 한계와 주의사항",desc:"환각, 편향, 기밀 정보 유출 주의",url:"index.html#s1-5",kw:"환각 hallucination 편향 한계"},
  {title:"1.6 RAG (검색 증강 생성)",desc:"RAG 개념, 벡터 데이터베이스, 임베딩",url:"module1-2.html#s1-6",kw:"RAG 검색 증강 벡터 임베딩"},
  {title:"1.7 AI 에이전트와 Agentic AI",desc:"에이전트 개념, 자율 실행, 도구 사용",url:"module1-2.html#s1-7",kw:"에이전트 Agentic AI 자율 도구"},
  {title:"1.8 PM/PL 필수 AI 용어 사전",desc:"AI 핵심 용어 50+ 정리",url:"module1-2.html#s1-8",kw:"용어 사전 개념 정의"},
  {title:"1.9 AI 엔지니어링 4년간의 진화",desc:"2022~2026 AI 기술 발전 타임라인",url:"module1-2.html#s1-9",kw:"AI 역사 진화 타임라인"},
  {title:"1.10 멀티모달 AI와 No-code 빌더",desc:"이미지/영상 처리, No-code 플랫폼",url:"module1-2.html#s1-10",kw:"멀티모달 이미지 영상 No-code"},
  {title:"2.1 PRD 작성",desc:"AI로 제품 요구사항 문서 작성",url:"module2-1.html#s2-1",kw:"PRD 요구사항 제품 기획"},
  {title:"2.2 기획서/제안서 자동 생성",desc:"AI 활용 기획서 자동 작성",url:"module2-1.html#s2-2",kw:"기획서 제안서 자동 생성"},
  {title:"2.3 요구사항 정의서 작성",desc:"요구사항 명세, 기능/비기능 정의",url:"module2-1.html#s2-3",kw:"요구사항 정의서 기능 비기능"},
  {title:"2.4 회의록/보고서 자동 정리",desc:"회의록 자동화, 액션아이템 추출",url:"module2-1.html#s2-4",kw:"회의록 보고서 자동 정리"},
  {title:"2.5 프롬프트 템플릿 활용법",desc:"재사용 프롬프트 템플릿 설계",url:"module2-2.html#s2-5",kw:"프롬프트 템플릿 재사용"},
  {title:"2.6 PL 프로젝트 관리 문서",desc:"WBS, 일정표, 리스크 관리 문서",url:"module2-2.html#s2-6",kw:"PL 프로젝트 관리 WBS 일정"},
  {title:"2.7 AI 문서 품질 관리",desc:"AI 생성 문서의 품질 검증 방법",url:"module2-2.html#s2-7",kw:"문서 품질 검증 관리"},
  {title:"2.8 스펙 문서 및 API 명세",desc:"기술 스펙, API 명세서 작성",url:"module2-2.html#s2-8",kw:"스펙 API 명세 기술문서"},
  {title:"3.1 플로우차트 생성",desc:"Mermaid로 업무 흐름도 생성",url:"module3.html#s3-1",kw:"플로우차트 Mermaid 흐름도"},
  {title:"3.2 시스템 아키텍처 다이어그램",desc:"시스템 구조도 AI 생성",url:"module3.html#s3-2",kw:"아키텍처 시스템 구조 다이어그램"},
  {title:"3.3 ER 다이어그램",desc:"데이터베이스 관계도 생성",url:"module3.html#s3-3",kw:"ER 다이어그램 데이터베이스 관계"},
  {title:"3.4 사용자 여정 맵",desc:"고객 경험 여정 시각화",url:"module3.html#s3-4",kw:"사용자 여정 고객 경험 UX"},
  {title:"3.5 AI 도구별 도식화 비교",desc:"Mermaid, draw.io, Excalidraw 비교",url:"module3.html#s3-5",kw:"Mermaid draw.io Excalidraw"},
  {title:"3.6 시퀀스 다이어그램",desc:"API 호출 시퀀스 시각화",url:"module3.html#s3-6",kw:"시퀀스 다이어그램 API 호출"},
  {title:"4.1 시장 조사 및 트렌드 분석",desc:"AI 활용 시장 리서치",url:"module4-1.html#s4-1",kw:"시장 조사 트렌드 리서치"},
  {title:"4.2 경쟁사 분석 프레임워크",desc:"경쟁사 분석 자동화",url:"module4-1.html#s4-2",kw:"경쟁사 분석 프레임워크 SWOT"},
  {title:"4.3 사용자 페르소나 생성",desc:"AI로 페르소나 자동 생성",url:"module4-1.html#s4-3",kw:"페르소나 사용자 타겟"},
  {title:"4.4 데이터 수집 및 정리",desc:"데이터 크롤링, 정리 자동화",url:"module4-1.html#s4-4",kw:"데이터 수집 정리 크롤링"},
  {title:"4.5 리서치 결과 보고서 작성",desc:"리서치 보고서 AI 작성",url:"module4-1.html#s4-5",kw:"리서치 보고서 결과"},
  {title:"4.6 AI 검색 도구 활용",desc:"Perplexity, 딥리서치 활용법",url:"module4-2.html#s4-6",kw:"Perplexity 검색 딥리서치"},
  {title:"4.7 팩트 체크 및 검증",desc:"AI 결과물 사실 확인 방법",url:"module4-2.html#s4-7",kw:"팩트 체크 검증 사실확인"},
  {title:"4.8 인터뷰 설계 및 분석",desc:"사용자 인터뷰 AI 분석",url:"module4-2.html#s4-8",kw:"인터뷰 설계 분석 사용자"},
  {title:"4.9 A/B 테스트 설계",desc:"실험 설계와 가설 검증",url:"module4-2.html#s4-9",kw:"AB 테스트 실험 가설"},
  {title:"5.1 바이브 코딩이란?",desc:"자연어로 코딩하는 새로운 패러다임",url:"module5-1.html#s5-1",kw:"바이브 코딩 자연어 코딩"},
  {title:"5.2 Claude Code 시작하기",desc:"설치, 기본 사용법, 프로젝트 설정",url:"module5-1.html#s5-2",kw:"Claude Code 설치 시작"},
  {title:"5.3 프롬프트로 웹페이지 만들기",desc:"HTML/CSS/JS 자동 생성",url:"module5-1.html#s5-3",kw:"웹페이지 HTML CSS 프롬프트"},
  {title:"5.4 반복 개선으로 완성도 높이기",desc:"피드백 루프, 점진적 개선",url:"module5-1.html#s5-4",kw:"반복 개선 피드백 완성도"},
  {title:"5.5 실전 프로젝트: 랜딩페이지",desc:"랜딩페이지 프로젝트 실습",url:"module5-1.html#s5-5",kw:"랜딩페이지 프로젝트 실전"},
  {title:"5.6 Claude Code 핵심 용어",desc:"MCP, 컨텍스트, 토큰 등 핵심 개념",url:"module5-2.html#s5-6",kw:"MCP 컨텍스트 토큰 핵심"},
  {title:"5.7 유용한 스킬 & 활용법",desc:"Claude Code 스킬 활용",url:"module5-2.html#s5-7",kw:"스킬 활용법 Claude Code"},
  {title:"5.8 커뮤니티 스킬 & 확장 생태계",desc:"오픈소스 스킬, MCP 서버 생태계",url:"module5-2.html#s5-8",kw:"커뮤니티 스킬 오픈소스 MCP"},
  {title:"5.9 PL을 위한 실전 활용 전략",desc:"PL 업무에 Claude Code 활용",url:"module5-3.html#s5-9",kw:"PL 실전 전략 업무"},
  {title:"5.10 웹 게시판 & MCP 테스트",desc:"게시판 구축, MCP 서버 테스트",url:"module5-3.html#s5-10",kw:"게시판 MCP 테스트 서버"},
  {title:"5.11 Flutter 앱 & APK 빌드",desc:"Flutter 앱 개발과 빌드",url:"module5-4.html#s5-11",kw:"Flutter APK 모바일 앱"},
  {title:"5.12 기존 소스 대규모 개선",desc:"레거시 코드 리팩토링 전략",url:"module5-4.html#s5-12",kw:"레거시 리팩토링 대규모 개선"},
  {title:"5.13 업무 능률 극대화 전략",desc:"개발 생산성 향상 전략",url:"module5-4.html#s5-13",kw:"업무 능률 생산성 극대화"},
  {title:"5.14 AI 활용 DevOps & CI/CD",desc:"GitHub Actions, Docker, 배포 자동화",url:"module5-5.html#s5-14",kw:"DevOps CICD GitHub Actions Docker 배포"},
  {title:"5.15 AI 활용 테스팅 전략",desc:"TDD, 단위 테스트, E2E 테스트 자동화",url:"module5-5.html#s5-15",kw:"TDD 테스트 Jest JUnit E2E Playwright"},
  {title:"5.16 AI 활용 API 설계",desc:"REST API 설계, OpenAPI, 인증",url:"module5-5.html#s5-16",kw:"REST API OpenAPI Swagger Express Spring"},
  {title:"6.1 PM vs PL 역할 비교",desc:"PM과 PL의 역할 차이점",url:"module6-1.html#s6-1",kw:"PM PL 역할 비교 차이"},
  {title:"6.2 PL의 핵심 역량",desc:"PL에게 필요한 핵심 역량",url:"module6-1.html#s6-2",kw:"PL 역량 핵심 리더십"},
  {title:"6.3 프로젝트 일정 관리",desc:"WBS, 간트차트, 일정 추적",url:"module6-1.html#s6-3",kw:"일정 관리 WBS 간트차트"},
  {title:"6.4 리스크 & 이슈 관리",desc:"프로젝트 리스크 식별과 대응",url:"module6-2.html#s6-4",kw:"리스크 이슈 관리 대응"},
  {title:"6.5 팀 리딩과 커뮤니케이션",desc:"효과적인 팀 소통과 리더십",url:"module6-2.html#s6-5",kw:"팀 리딩 커뮤니케이션 소통"},
  {title:"6.6 AI로 PL 업무 자동화",desc:"PL 반복 업무 AI 자동화",url:"module6-2.html#s6-6",kw:"PL 업무 자동화 AI"},
  {title:"6.7 AI 시대 역할 변화",desc:"AI가 바꾸는 PM/PL 역할",url:"module6-3.html#s6-7",kw:"AI 시대 역할 변화 미래"},
  {title:"6.8 AI 거버넌스 및 윤리",desc:"AI 윤리, 거버넌스 프레임워크",url:"module6-3.html#s6-8",kw:"거버넌스 윤리 규제 정책"},
  {title:"6.9 애자일/스크럼 심화",desc:"스크럼, 칸반, 스프린트 실무",url:"module6-3.html#s6-9",kw:"애자일 스크럼 칸반 스프린트"},
  {title:"7.1 SaaS 기획~MVP 출시",desc:"SaaS 제품 기획부터 출시까지",url:"module7-1.html#s7-1",kw:"SaaS MVP 기획 출시"},
  {title:"7.2 레거시 마이그레이션",desc:"레거시 시스템 현대화 전략",url:"module7-1.html#s7-2",kw:"레거시 마이그레이션 현대화"},
  {title:"7.3 AI 도구 도입 제안",desc:"조직에 AI 도구 도입 제안서 작성",url:"module7-2.html#s7-3",kw:"AI 도입 제안 조직"},
  {title:"7.4 AI 툴 조합 업무 활용",desc:"여러 AI 도구를 조합한 워크플로우",url:"module7-2.html#s7-4",kw:"AI 도구 조합 워크플로우"},
  {title:"7.5 국내 AI 도입 현황",desc:"한국 기업 AI 도입 사례",url:"module7-2.html#s7-5",kw:"국내 AI 도입 사례 현황"},
  {title:"8.1 AI 도구 요금제 비교",desc:"ChatGPT, Claude, Copilot 요금제",url:"module8-1.html#s8-1",kw:"요금제 비용 구독 가격"},
  {title:"8.2 토큰 비용 계산",desc:"토큰 개념, 비용 추정, 최적화",url:"module8-1.html#s8-2",kw:"토큰 비용 계산 최적화"},
  {title:"8.3 AI 도입 ROI 산출",desc:"투자 수익률 계산, 예산 설득",url:"module8-1.html#s8-3",kw:"ROI 투자 수익 예산"},
  {title:"8.4 예산 편성 및 설득",desc:"AI 도구 예산 확보 전략",url:"module8-2.html#s8-4",kw:"예산 편성 설득 경영진"},
  {title:"8.5 AI 도구 선정 매트릭스",desc:"도구 평가 기준, 점수 매트릭스",url:"module8-2.html#s8-5",kw:"도구 선정 매트릭스 평가"},
  {title:"9.1 AI 코딩 도구 생태계",desc:"Claude Code, Cursor, Copilot, Windsurf 비교",url:"module9-1.html#s9-1",kw:"코딩 도구 Cursor Copilot Windsurf"},
  {title:"9.2 AI 보안 필수 가이드",desc:"프롬프트 인젝션, 데이터 유출 방지",url:"module9-1.html#s9-2",kw:"보안 인젝션 데이터 유출 API키"},
  {title:"9.3 AI 거버넌스 프레임워크",desc:"AI 정책, 규제 대응, GDPR",url:"module9-2.html#s9-3",kw:"거버넌스 프레임워크 정책 GDPR"},
  {title:"9.4 AI 도구 도입 로드맵",desc:"단계별 AI 도구 도입 계획",url:"module9-2.html#s9-4",kw:"로드맵 도입 계획 단계"},
  {title:"9.5 개발자 AI 학습 로드맵",desc:"Java/Python 개발자 AI 학습 경로",url:"module9-2.html#s9-5",kw:"개발자 학습 Java Python LangChain"},
  {title:"10.1 No-Code AI 자동화",desc:"Zapier, Make 등 No-Code 자동화",url:"module10-1.html#s10-1",kw:"No-Code 자동화 Zapier Make"},
  {title:"10.2 컨텍스트 엔지니어링",desc:"AI 컨텍스트 최적화 전략",url:"module10-1.html#s10-2",kw:"컨텍스트 엔지니어링 최적화"},
  {title:"10.3 추론 모델 & 확장된 사고",desc:"o1, Claude 추론 모드, 사고 과정",url:"module10-1.html#s10-3",kw:"추론 모델 사고 reasoning o1"},
  {title:"10.4 멀티모달 AI 실무",desc:"이미지/영상/음성 AI 활용",url:"module10-2.html#s10-4",kw:"멀티모달 이미지 영상 음성"},
  {title:"10.5 AI 네이티브 팀 협업",desc:"AI 중심 팀 워크플로우 구축",url:"module10-2.html#s10-5",kw:"AI 네이티브 팀 협업 워크플로우"}
];
